### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Tchilo** [Tchilo/Ruby-capstone#37]
### Link to kanban board: [click here](https://github.com/Tchilo/Ruby-capstone/projects/1)

We are four people working in this team. Here is the team member who is assigned tasks listed for:

- Team member # 1 @isaka-lumato 
- Team member # 2 @Tchilo 
- Team member # 3 @yahyaelganyni1 
- Team member # 4 @mahbubul14

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Tchilo, @mahbubul14, @isaka-lumato, and @yahyaelganyni1,

Good job so far!
✔️ Correct number of Kanban columns
✔️ Cards have complexity weights.
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
**NOTE: Please, do not open a new issue for re-reviews. You should use the same issue submitted for the first review**
- [x] Currently, members 1, 2, 3, and 4 have the following total points: 17.75, 11.5, 13.5, and 13 respectively. No member is supposed to have 5 (or more) points more than another member. Kindly resolve this. 
- [x] Team member 2 is missing the card for **`All Genre class properties visible in the diagram should be defined and set up in the constructor method`**. Kindly add that
- [x] I think Team member 3 is missing the card for `The following options should be available: ...` Kindly add it.
- [x] The task `Create a Book class in a separate .rb file[[Team member #1] #12` is missing number of points. Kindly add it.
- [x] As highlighted in the image below, some of your tasks are missing descriptions. Kindly add them
  
  ![tchilo-desc](https://user-images.githubusercontent.com/36542986/149906372-91c1f205-ddfd-4f84-851d-85d97e1ca2fc.jpg)
- [ ] I think there is a repetition of tasks. Kindly resolve it

  ![yah](https://user-images.githubusercontent.com/36542986/149909521-2e14c43d-a947-4dcb-9204-caaae0361247.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this thread if something is not 100% clear.

**_Please, do not open a new issue for re-reviews. You should use the same issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikethreels** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [x] as the previous CR already mentioned there is too much difference in points between each team member, please communicate with each other on how much time a task takes and divide the points evenly between each member. right now it is divided as reflected below (make sure there is not more than 5 points difference between 2 team members).
- team member 1 - 10.85 points
- team member 2 - 9.5 points
- team member 3 - 13.5 points
- team member 4 - 16 points
- [x] the previous CR also mentioned that there are some tasks without description please make sure every task has a description, below I've made a list of all the tasks without a description please make sure to add this before requesting another code review.
- [2pt]All data should be preserved by saving collections in .json files. [Team member #1]
- [0.5pt]All Genre class properties visible in the diagram should be defined and set up in the constructor method.[Team member #2]
- [0.5pt]Add unit tests for all implemented methods [Team member #1]
- [1pt]All Book class properties visible in the diagram should be defined and set up in the constructor method [Team member # 1]
- [0.75pt]Create a Label class with an association to the Item class (in a separate .rb file).[Team member #1]
- [1pt]All data should be preserved by saving collections in .json files. [Team member #2]
- [1pt]All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method. [Team member #2]
- [1pt]Create Genre class with an association to the Item class (in a separate .rb file).[Team member #2]
- [0.5pt]Create a Book class in a separate .rb file[[Team member #1]
- [1pt]Create MusicAlbum class in a separate .rb file [Team member #2]

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahbubul14** [comment]
@mikethreels Thanks. We have updated all the required changes you suggested.

**Comment by elyor-doniyorov** [comment]
Hi Team👋, 

In my opinion, your Kanban board is ready!  There is nothing else to say other than... it's time to move forward and start the journey :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Tchilo** [comment]
Thanks for the reviews 😄.
